name: Sync to Gitee

on:
  push:
    branches: 
      - main
      - master
  schedule:
    - cron: '0 1 * * *'  # UTC 1:00 即北京时间 9:00
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Mirror to Gitee
        uses: Yikun/hub-mirror-action@v1.4
        with:
          # 源和目标
          src: github/Assianc
          dst: gitee/Assianc
          
          # 使用 HTTPS 而不是 SSH
          clone_style: https
          
          # Gitee 私人令牌
          dst_token: ${{ secrets.GITEE_TOKEN }}
          
          # 基本配置
          account_type: user
          force_update: true
          debug: true
          timeout: '30m'
          
          # 缓存配置
          cache_path: /github/workspace/hub-mirror-cache
