name: Sync to Gitee

on:
  push:
    branches: 
      - main
      - master
  schedule:
    - cron: '0 1 * * *'  # UTC 1:00 即北京时间 9:00
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout source code
        uses: actions/checkout@v3

      # 配置 SSH
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITEE_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitee.com >> ~/.ssh/known_hosts

      # 同步到 Gitee
      - name: Mirror to Gitee
        uses: Yikun/hub-mirror-action@v1.4
        with:
          src: github/Assianc
          dst: gitee/Assianc
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          account_type: user
          clone_style: ssh
          force_update: true
          debug: true
          timeout: '30m'
          static_list: ""  # 如果需要指定仓库，在这里添加，用逗号分隔
